// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Залогинивает пользователя и выдает токены",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход в систему",
                "parameters": [
                    {
                        "description": "Данные пользователя для входа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные / параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные данные для входа",
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/ping": {
            "get": {
                "description": "Возвращает pong, если сервис авторизации работает",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Проверка доступности auth-сервиса",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Выдает пользователю пару новых токенов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновление токенов",
                "parameters": [
                    {
                        "description": "Пара старых токенов",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.RefreshTokensRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Новые токены выданы",
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.RefreshTokensResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные / параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Создает нового пользователя в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Данные пользователя для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь зарегистрирован",
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные / параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Пользователь с такими данными уже существует",
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_dormitory-life_auth_internal_server_request_models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_dormitory-life_auth_internal_server_request_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_dormitory-life_auth_internal_server_request_models.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_dormitory-life_auth_internal_server_request_models.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "dormitory_id": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_dormitory-life_auth_internal_server_request_models.RefreshTokensRequest": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "dormitoryId": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "github_com_dormitory-life_auth_internal_server_request_models.RefreshTokensResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_dormitory-life_auth_internal_server_request_models.RegisterRequest": {
            "type": "object",
            "properties": {
                "dormitory_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_dormitory-life_auth_internal_server_request_models.RegisterResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "dormitory_id": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Dormitory Life Auth API",
	Description:      "API сервиса авторизации Dormitory Life",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
